<a href="https://colab.research.google.com/github/thakuranupsingh1/ipcv/blob/main/experimnt5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np

In [ ]:
img=cv2.imread('/content/WhatsApp Image 2026-03-23 at 9.13.53 AM.jpeg',0)

In [ ]:
gauss=img + np.random.normal(0,60,img.shape)

In [ ]:
print(gauss)

[[  76.51300149  -11.92054124   21.74472449 ...  105.86368634
   -72.42053415  -73.72379051]
 [ -22.26981963 -117.71650785   -6.92067446 ...    4.2120358
   -59.31101171   -3.7219046 ]
 [  40.76445279   -2.2800385    65.131943   ...   86.6920087
    20.0432883    -7.01739091]
 ...
 [ 168.65492639  282.61402328  362.98626243 ...  102.95428707
   -29.87163068   -8.64063386]
 [ 229.14586045  139.48213672  299.23259443 ...  123.33010227
    19.20031497   11.15055201]
 [ 188.82387162  352.48722721  224.54435768 ...   69.32535611
   -31.71978419  -10.96976357]]


In [ ]:
gauss=np.clip(gauss,0,255).astype(np.uint8)

In [ ]:
print(gauss)

[[ 76   0  21 ... 105   0   0]
 [  0   0   0 ...   4   0   0]
 [ 40   0  65 ...  86  20   0]
 ...
 [168 255 255 ... 102   0   0]
 [229 139 255 ... 123  19  11]
 [188 255 224 ...  69   0   0]]


In [ ]:
sp=img.copy()

In [ ]:
prob=0.02
rand=np.random.rand(*img.shape)
sp[rand<prob]=0

In [ ]:
sp[rand>1-prob]=255

In [ ]:
print(rand)

[[0.70119138 0.30622772 0.94800979 ... 0.53525638 0.76831301 0.78592523]
 [0.99022132 0.94186937 0.31114114 ... 0.14407115 0.3815844  0.11023529]
 [0.97556996 0.38894177 0.86218828 ... 0.16420376 0.07486666 0.03314478]
 ...
 [0.98767871 0.75528467 0.69081587 ... 0.79273582 0.96104662 0.17196933]
 [0.10321655 0.10348188 0.14513291 ... 0.39152282 0.39948075 0.15772321]
 [0.45051276 0.92400655 0.12298714 ... 0.56246708 0.37733037 0.73686749]]


In [ ]:
cv2.imwrite("gauss.jpg",gauss)

True

In [ ]:
from google.colab import files
files.download("gauss.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
cv2.imwrite("sp.jpg",sp)

True

In [ ]:
files.download("sp.jpg")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
mean_filt=cv2.blur(gauss,(3,3))

In [ ]:
median_filt =cv2.medianBlur(sp,3)

In [ ]:
cv2.imwrite("gaussapplied.jpg",median_filt)

True

In [ ]:
files.download("gaussapplied.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
cv2.imwrite("spapplied.jpg",median_filt)

True

In [ ]:
files.download("spapplied.jpg")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>